<div id="popup-modal">

<div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}' class="collapsible">
    <?php
    //VARIABLES
    $currentProductPrice = $block->getProductPrize();
    $bankName = $block->getBankName()->getData();
    $minAmount = [];
    ?>
        <?php foreach ($bankName as $bank): ?>
        <div class="head-accordion" data-role="collapsible">
            <div data-role="trigger">
                <span><?php echo $bank['bank_name']; ?></span>
            </div>
        </div>
        <div data-role="content" class="content-accodion">
            <table border="1px">
                <?php
                    echo " <tr>";
                    echo "<th>EMI PLANS</th>";
                    echo "<th>Interest Amount(%)</th>";
                    echo "<th>Final Amount </th>";
                    echo "</tr>";
                    $data = $block->getEmiDetails($bank['bank_name']);
                    foreach ($data->getData() as $emidetails)
                    {
                        $duration = $emidetails['duration'];
                        $rateOfInterest = $emidetails['duration'];
                        // $emiamount = $block->getEmiAmount($currentProductPrice, $emidetails['interest_rate'], $duration);
                        // $totalAmount = $block->getTotalAmount($currentProductPrice, $rateOfInterest,$emiamount,$duration);
                        // $monthlyAmount = $block->getMonthlyAmount($totalAmount,$duration,$emiamount);
                        // $interestPM = ($totalAmount - $currentProductPrice)/$duration;
                        // $interestPM = $block->getMonthlyInterst($currentProductPrice,$duration,$emiamount);
                        $emiamount = $block->getEmiAmount($currentProductPrice, $emidetails['interest_rate'], $emidetails['duration']);
                        $totalAmount = $emiamount * $duration;
                        $monthlyAmount = $totalAmount/ $duration;
                        $interestPM = ($totalAmount - $currentProductPrice);

                        array_push($minAmount, $monthlyAmount);
                        
                        echo "<tr>";
                        echo "<td>" . $duration."EMIs @ $". round($emiamount,2)."</td>";
                        // echo "<td>" . $monthlyAmount."RS | ". $duration." Months "."</td>";
                        echo "<td>"."$".round($interestPM, 2)." (".$emidetails['interest_rate']."%)"."</td>";
                        echo "<td>"."$".round($totalAmount,2)."</td>";
                        echo "</tr>";
                    }
                ?>
            </table>    
        </div>  
        <?php endforeach; ?> 
        
    </div>
</div>
<div id="lowest_emi_amount">EMI Starting From<a href="#">$<?php echo round(min($minAmount),2);?></a></div>

