<div id="ajaxresponse"></div>
<?php
$ajaxurl = $block->getAjaxUrl();
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Ambab_EmiCalculator/js/custom": {
                    "AjaxUrl": "<?php echo $ajaxurl; ?>",
                    "bank_name": "<?php echo $bank_name; ?>",
                    "emiamount": "<?php echo $emiamount; ?>",
                    "duration": "<?php echo $duration; ?>",
                    "rateOfInterest": "<?php echo $rateOfInterest; ?>",
                    "interestPM": "<?php echo $interestPM; ?>",
                    "totalAmount": "<?php echo $totalAmount; ?>",
                }
            }
        }
</script>
