<div id="popup" style="display: none;"> 
<?php
   //VARIABLES
        $blockobj1 = $block->getLayout()->createBlock('Ambab\EmiCalculator\Block\Catalog\Product\Js');
        $emioptions = $blockobj1->getEmiOptionalYesNo();        
        $blockobj = $block->getLayout()->createBlock('Ambab\EmiCalculator\Block\Catalog\Product\View');
        $bankName = $blockobj->getBankNameData();
        // $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        // $cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
        // $currentProductPrice = $cart->getQuote()->getBaseSubtotal();
        $currentProductPrice = $blockobj->getGrandTotal();
    ?>
    <div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}' class="collapsible">
    
            <?php foreach ($bankName as $bank): ?>
            <div class="head-accordion" data-role="collapsible">
                <div data-role="trigger">
                    <span><?php echo $bank['bank_name']; ?></span>
                </div>
            </div>
            
            
            <div data-role="content" class="content-accodion">
                <table border="1px">
                    <?php
            
                        echo " <tr>";
                        echo "<th> </th>";
                        echo "<th>EMI PLANS</th>";
                        echo "<th>Interest Amount(%)</th>";
                        echo "<th>Final Amount </th>";
                        echo "</tr>";
                        $data = $blockobj->getEmiDetails($bank['bank_name']);
            
                        foreach ($data->getData() as $emidetails)
                        {
                            $duration = $emidetails['duration'];
                            $emiamount = $blockobj->getEmiAmount($currentProductPrice, $emidetails['interest_rate'], $emidetails['duration']);
                            $totalAmount = $emiamount * $duration;
                            $monthlyAmount = $totalAmount/ $duration;
                            $interestPM = ($totalAmount - $currentProductPrice);
                            echo "<tr>";
                            echo "<th> <input type='radio' name='select' /></th>";
                            echo "<td>" . $emidetails['duration']."EMIs @ $". round($emiamount,2)."</td>";
                            echo "<td>"."$".round($interestPM, 2)." (".$emidetails['interest_rate']."%)"."</td>";
                            echo "<td>"."$".round($totalAmount,2)."</td>";
                            echo "</tr>";
                        }
                    ?>
                </table>    
            </div>  
            <?php endforeach;?> 
        </div>
    </div>
</div>

<script>
    var emioptions = <?php echo json_encode($emioptions); ?>;
</script>